language: go
go:
  - 1.6.3
  - 1.7.1
  - tip
script:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go test
notifications:
  email:
    on_success: change
    on_failure: always